language: perl

env:
  matrix:
    - OS=netbsd
    - OS=debian
    - OS=ubuntu
    - OS=centos
    - OS=opensuse
    - OS=alpine
    - OS=bash
  global:
    - PATH=$HOME/.local/bin:$PATH
    
perl:
  - "5.22"

sudo: required

services:
  - docker

before_install:
  - pip install --user awscli
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER
  - aws s3 sync s3://madworx/docshell-build/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER
  
install:
  - cpanm --quiet --installdeps --notest ./test
  - cd test

script:
  - make -s OS=${OS} > ~/$TRAVIS_BUILD_NUMBER/${OS}.tap

jobs:
  include:
    - stage: Generate report
      script:
        - export DIR=~/$TRAVIS_BUILD_NUMBER ; ./publish-report.sh 
      after_success:
        - aws s3 rm --recursive s3://madworx/docshell-build/$TRAVIS_BUILD_NUMBER

after_success:
  - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://madworx/docshell-build/$TRAVIS_BUILD_NUMBER
